name: PullRequest
  on: [pull_request]

jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "${{envkey.POSTGRES_USER}}"
          envkey_POSTGRES_PASSWORD: "${{envkey.POSTGRES_PASSWORD}}"
          envkey_POSTGRES_DB: "${{envkey.POSTGRES_DB}}"
          envkey_DATABASE_URL: "${{envkey.DATABASE_URL}}"
          file_name: .env.test
